# Generated by Django 3.0.2 on 2020-01-12 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_auto_20200112_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='recentlookup',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='search.User'),
        ),
    ]
