# Generated by Django 3.0.2 on 2020-01-13 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0006_auto_20200113_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(default='penguin.jpg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='view_pager_image_1',
            field=models.ImageField(default='penguin.jpg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='view_pager_image_2',
            field=models.ImageField(default='penguin.jpg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='view_pager_image_3',
            field=models.ImageField(default='penguin.jpg', upload_to=''),
        ),
    ]
