# Generated by Django 3.0.2 on 2020-01-14 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0007_auto_20200113_1029'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_num', models.BigIntegerField()),
                ('card_name', models.TextField()),
                ('card_validate_num', models.IntegerField()),
                ('card_cvc', models.ImageField(upload_to='')),
                ('uesr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.User')),
            ],
        ),
    ]
